# Generated by Django 5.1.2 on 2024-10-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userresetpasswordtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResetPasswordToken',
        ),
    ]
